name: dsci522
channels:
- conda-forge
- defaults
dependencies:
- python=3.12.11
- ipython=9.5.0
- ipykernel=6.30.1
- matplotlib=3.10.6
- pandas=2.3.2
- scikit-learn=1.7.2
- seaborn=0.13.2
- scienceplots=2.2.0
- pip=25.2
