name: dsci522
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - ipykernel=6.30.1
  - matplotlib=3.10.6
  - pandas=2.3.2
  - scikit-learn=1.7.2
  - seaborn=0.13.2
  - scienceplots=2.2.0
  - notebook=6.5.4
  - pandera=0.20.4
  - click=8.2.1
  - quarto=1.8.26
  - pip=25.3
  - pip:
      - deepchecks==0.18.1